---
- name: "Create tmp directory"
  file:
    path: "{{ tmp_dir }}"
    state: directory
    mode: 0755
  tags: metallb

- name: "Install MetalLB - Create Namespace"
  shell: "kubectl apply -f {{ metallb_namespace_yaml_url }}"
  tags: metallb

- name: "Install MetalLB"
  shell: "kubectl apply -f {{ metallb_yaml_url }}"
  tags: metallb

- name: "Execute OpenSSL"
  command: "openssl rand -base64 128"
  register: openssl_key
  tags: metallb

- debug: msg="{{ openssl_key.stdout }}"

- name: "Install MetalLB - Create a Generic"
  shell: "kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey=\"{{ openssl_key.stdout }}\""
  tags: metallb

- name: "Create configmap file"
  template:
    src: metallb-layer-2-config.yml.j2
    dest: "{{ tmp_dir }}/metallb-layer-2-config.yml"
  tags: metallb

- name: "Create MetalLB configmap in kubernetes"
  shell: "kubectl apply -f {{ tmp_dir }}/metallb-layer-2-config.yml"
  tags: metallb

- name: "Clean-up"
  file:
    path: "{{ tmp_dir }}"
    state: absent
  ignore_errors: yes
  tags: metallb
