---

- name: Reset Kubernetes component
  shell: "kubeadm reset --force"
  register: reset_cluster

- debug: msg="{{ master_ip }}"

- name: Join to Kubernetes cluster
  when: reset_cluster is succeeded
  shell: |
    kubeadm join --token {{ token }} \
                --discovery-token-unsafe-skip-ca-verification \
                {{ apiserver_ip }}:6443
  register: join_cluster
  notify:
    - Recreate kube-dns
  # {{ master_ip }}:6443
